
Aborted!
Exception ignored in: <module 'threading' from '/home/thomas/.local/share/uv/python/cpython-3.11.7-linux-x86_64-gnu/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/home/thomas/.local/share/uv/python/cpython-3.11.7-linux-x86_64-gnu/lib/python3.11/threading.py", line 1560, in _shutdown
    atexit_call()
  File "/home/thomas/.local/share/uv/python/cpython-3.11.7-linux-x86_64-gnu/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/home/thomas/.local/share/uv/python/cpython-3.11.7-linux-x86_64-gnu/lib/python3.11/threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "/home/thomas/.local/share/uv/python/cpython-3.11.7-linux-x86_64-gnu/lib/python3.11/threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
